##################################################################################################
# poc service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: poc-service
  labels:
    app: poc-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: poc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-service
      version: v1
  template:
    metadata:
      labels:
        app: poc-service
        version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: docker.pkg.github.com/no5013/poc-service/poc-service:1.0.0
          imagePullPolicy: IfNotPresent
          name: poc-service
          ports:
            - containerPort: 80