##################################################################################################
# poc service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: poc-service
  labels:
    app: poc-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: poc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-service
      version: v1
  template:
    metadata:
      labels:
        app: poc-service
        version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: docker.io/no5013/poc-service:1.0.0
          imagePullPolicy: Always
          name: poc-service
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-config
              mountPath: "/deployments/config"
              readOnly: true
          env:
#            - name: spring.profiles.active
#              valueFrom:
#                configMapKeyRef:
#                  name: env-config
#                  key: spring.profile
            - name: SECRET_CODE_LIVES
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: secret.code.lives
      volumes:
        - name: application-config
          configMap:
            name: game-config
            items:
              - key: game.properties
                path: game.properties
              - key: ui.properties
                path: ui.properties
              - key: application.properties
                path: application.properties

