name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/no5013/poc-service/my-image-name:1.0.0


    - name: Push to Registry
      run: |
        docker login docker.pkg.github.com -u no5013
        docker push docker.pkg.github.com/no5013/poc-service/my-image-name:1.0.0